# Generated by Django 6.0.1 on 2026-02-24 23:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('plate_number', models.CharField(max_length=20, verbose_name='Plate Number')),
                ('make', models.CharField(blank=True, max_length=100, verbose_name='Make')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='Model')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Year')),
                ('odometer', models.PositiveIntegerField(default=0, verbose_name='Odometer')),
                ('fuel_type', models.CharField(default='gasoline', max_length=20, verbose_name='Fuel Type')),
                ('status', models.CharField(choices=[('available', 'Available'), ('in_use', 'In Use'), ('maintenance', 'In Maintenance'), ('retired', 'Retired')], default='available', max_length=20, verbose_name='Status')),
                ('assigned_to', models.UUIDField(blank=True, null=True, verbose_name='Assigned To')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'db_table': 'fleet_vehicle',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TripLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('date', models.DateField(verbose_name='Date')),
                ('origin', models.CharField(max_length=255, verbose_name='Origin')),
                ('destination', models.CharField(max_length=255, verbose_name='Destination')),
                ('distance_km', models.DecimalField(decimal_places=1, default='0', max_digits=8, verbose_name='Distance (km)')),
                ('driver_name', models.CharField(blank=True, max_length=255, verbose_name='Driver')),
                ('purpose', models.CharField(blank=True, max_length=255, verbose_name='Purpose')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_logs', to='fleet.vehicle')),
            ],
            options={
                'db_table': 'fleet_triplog',
                'ordering': ['-date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FuelLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('date', models.DateField(verbose_name='Date')),
                ('liters', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Liters')),
                ('cost', models.DecimalField(decimal_places=2, default='0', max_digits=10, verbose_name='Cost')),
                ('odometer', models.PositiveIntegerField(verbose_name='Odometer Reading')),
                ('full_tank', models.BooleanField(default=True, verbose_name='Full Tank')),
                ('station', models.CharField(blank=True, max_length=255, verbose_name='Station')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_logs', to='fleet.vehicle')),
            ],
            options={
                'db_table': 'fleet_fuellog',
                'ordering': ['-date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VehicleMaintenanceLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('maintenance_type', models.CharField(choices=[('preventive', 'Preventive'), ('corrective', 'Corrective'), ('inspection', 'Inspection / ITV')], default='corrective', max_length=20, verbose_name='Type')),
                ('date', models.DateField(verbose_name='Date')),
                ('description', models.TextField(verbose_name='Description')),
                ('cost', models.DecimalField(decimal_places=2, default='0', max_digits=10, verbose_name='Cost')),
                ('odometer', models.PositiveIntegerField(blank=True, null=True, verbose_name='Odometer Reading')),
                ('performed_by', models.CharField(blank=True, max_length=255, verbose_name='Workshop / Mechanic')),
                ('next_maintenance', models.DateField(blank=True, null=True, verbose_name='Next Maintenance')),
                ('next_odometer', models.PositiveIntegerField(blank=True, null=True, verbose_name='Next at Odometer')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='fleet.vehicle')),
            ],
            options={
                'db_table': 'fleet_maintenancelog',
                'ordering': ['-date'],
                'abstract': False,
            },
        ),
    ]
